processor-toolbox:
    processors:
      - { type: egg-processor,       name: egg }
      - { type: forward-fftw,        name: fft }
      - { type: convert-to-power,    name: to-ps }
      - { type: low-pass-filter,     name: lpf }
      - { type: basic-root-writer,   name: writer }

    connections:
      - signal: egg:header
        slot: fft:header
      - signal: egg:ts
        slot: fft:ts-fftw
      - signal: fft:fft
        slot: to-ps:fs-fftw-to-ps
      - signal: to-ps:ps
        slot: lpf:ps
      - signal: to-ps:ps
        slot: writer:ps
      - signal: lpf:ps
        slot: writer:lpf-ps

    run-queue:
      - egg

egg:
    filename: "/path/to/file.egg"
    egg-reader: egg3
    slice-size: 4096
    number-of-slices: 10

fft:
    transform-flag: ESTIMATE

lpf:
    # RC for cutoff frequency of 50 MHz
    rc: 3.1831e-9  

writer:
    output-file: "/path/to/file.root"
    file-flag: recreate
